[package]
name = "arse"
version = "0.1.0"
authors = ["Brandon Matthews <bmatthews@linkedin.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.3.0"
hamming = "0.1.3"
aes = "0.3.2"
block-modes = "0.3.3"
